### ISSUE TITLE
Minor bugs

### ISSUE THREAD

**Issue by changchuming** [thomasahle/codenames#1]
Slight bugs in get_glove.sh. Fixed them for you.

> mkdir dataset
cd dataset
wget --no-check-certificate http://nlp.stanford.edu/data/glove.6B.zip
unzip glove.6B.zip glove.6B.300d.txt
rm glove.6B.zip
cd ..
python3 convert.py

**Comment by thomasahle** [comment]
Thank you, I've updated the code
